-- Gerado por node scripts/me-conta-seed.mjs. Edite content/me-conta/cards.json.
insert into momentos.me_conta_cards (slug, age_band, level, question, tip) values
('24-lev-bicho', '2-4'::momentos.age_band, 'leve', 'Se o seu travesseiro fosse um bicho, qual seria?', 'Você começa. Faça o som do bicho que escolheu.'),
('24-lev-cor', '2-4'::momentos.age_band, 'leve', 'Qual cor você queria colocar no céu hoje?', 'Aponte uma cor que esteja perto de vocês.'),
('24-lev-barulho', '2-4'::momentos.age_band, 'leve', 'Que barulho o seu pé faria se pudesse falar?', 'Responda com um som antes de usar palavras.'),
('24-lev-comida', '2-4'::momentos.age_band, 'leve', 'Se a banana usasse chapéu, qual chapéu seria?', 'Deixe a resposta virar uma cena engraçada.'),
('24-lev-objeto', '2-4'::momentos.age_band, 'leve', 'Qual brinquedo daqui você levaria para a Lua?', 'Escolha o seu primeiro e diga por quê.'),
('24-lev-danca', '2-4'::momentos.age_band, 'leve', 'Como seria a dança de um elefante pequenininho?', 'Façam um movimento juntos, sem sair do lugar.'),
('24-med-sorriso', '2-4'::momentos.age_band, 'medio', 'O que fez você sorrir hoje?', 'Conte uma cena pequena do seu dia primeiro.'),
('24-med-colo', '2-4'::momentos.age_band, 'medio', 'Qual é o melhor lugar para ficar juntinho?', 'Aponte um lugar real da casa.'),
('24-med-ajuda', '2-4'::momentos.age_band, 'medio', 'Quando você quer uma ajuda minha?', 'Você começa contando quando gosta de receber ajuda.'),
('24-med-brinca', '2-4'::momentos.age_band, 'medio', 'Qual brincadeira nossa você quer repetir?', 'Se não lembrar, cite uma que vocês fizeram esta semana.'),
('24-med-som', '2-4'::momentos.age_band, 'medio', 'Que som da nossa casa você gosta de ouvir?', 'Façam silêncio por um instante para escutar.'),
('24-med-abraco', '2-4'::momentos.age_band, 'medio', 'Como é um abraço perfeito para você?', 'Pergunte antes de abraçar. A resposta também pode ser sem abraço.'),
('56-lev-comida', '5-7'::momentos.age_band, 'leve', 'Qual comida que eu gosto parece mais esquisita para você?', 'Ria da sua escolha antes de ouvir a dele.'),
('56-lev-casa', '5-7'::momentos.age_band, 'leve', 'Se a nossa casa tivesse pernas, para onde ela iria?', 'Descreva o caminho como se fosse uma aventura.'),
('56-lev-superpoder', '5-7'::momentos.age_band, 'leve', 'Que superpoder inútil seria muito divertido ter?', 'Escolha um poder bobo para quebrar o gelo.'),
('56-lev-bicho', '5-7'::momentos.age_band, 'leve', 'Se eu virasse um bicho amanhã, qual você acha que eu seria?', 'Peça a justificativa e deixe ela surpreender você.'),
('56-lev-nome', '5-7'::momentos.age_band, 'leve', 'Que nome você daria para uma nuvem que mora aqui?', 'Invente o seu nome primeiro.'),
('56-lev-roupa', '5-7'::momentos.age_band, 'leve', 'Qual roupa minha parece saída de uma história engraçada?', 'Não se defenda. Faça uma pose com ela.'),
('56-med-dia', '5-7'::momentos.age_band, 'medio', 'Qual foi a melhor parte do seu dia hoje?', 'Conte uma cena concreta do seu dia antes de perguntar.'),
('56-med-repetir', '5-7'::momentos.age_band, 'medio', 'Se pudéssemos repetir uma hora desta semana, qual seria?', 'Escolha uma hora simples, não um grande evento.'),
('56-med-aprender', '5-7'::momentos.age_band, 'medio', 'O que você poderia me ensinar a fazer?', 'Aceite ser aprendiz por um minuto.'),
('56-med-coragem', '5-7'::momentos.age_band, 'medio', 'Quando você se sentiu corajoso esta semana?', 'Você começa com uma coragem pequena sua.'),
('56-med-rir', '5-7'::momentos.age_band, 'medio', 'O que a gente faz junto que sempre acaba em risada?', 'Lembre uma cena que aconteceu de verdade.'),
('56-med-escolher', '5-7'::momentos.age_band, 'medio', 'Se você escolhesse nossa próxima brincadeira, o que seria?', 'Anote a ideia para fazer depois, se puder.'),
('56-fun-ouvir', '5-7'::momentos.age_band, 'fundo', 'Quando você queria que eu escutasse mais?', 'Conte primeiro uma vez em que você precisou ser ouvido. Depois escute sem corrigir.'),
('56-fun-medo', '5-7'::momentos.age_band, 'fundo', 'Tem alguma coisa que dá medo e que você quer me contar?', 'Diga que pode passar. Não peça explicações se a resposta não vier.'),
('56-fun-zangado', '5-7'::momentos.age_band, 'fundo', 'O que ajuda quando você fica zangado?', 'Fale de algo que ajuda você, sem ensinar uma resposta certa.'),
('56-fun-saudade', '5-7'::momentos.age_band, 'fundo', 'De quem ou de que momento você sente saudade?', 'Pode ser de uma pessoa, um lugar ou um dia. Não force lembranças.'),
('56-fun-juntos', '5-7'::momentos.age_band, 'fundo', 'Quando você sente que estamos bem juntinhos?', 'Descreva primeiro um momento seu, sem exigir que ele concorde.'),
('56-fun-desculpa', '5-7'::momentos.age_band, 'fundo', 'Tem algo por que você queria que eu pedisse desculpa?', 'Escute até o fim. Se houver algo concreto, peça desculpa sem se justificar.'),
('24-lev-sapato', '2-4'::momentos.age_band, 'leve', 'Se esse sapato passeasse sozinho, para onde iria?', 'Aponte um sapato e faça ele dar dois passinhos.'),
('24-lev-tambor', '2-4'::momentos.age_band, 'leve', 'Que coisa aqui faz um som de tambor?', 'Experimente bater de leve numa almofada antes de escolher.'),
('24-lev-nuvem', '2-4'::momentos.age_band, 'leve', 'Que cara faria uma nuvem com sono?', 'Faça uma careta bem devagar e espere a criança inventar outra.'),
('24-lev-pelucia', '2-4'::momentos.age_band, 'leve', 'O que seu bichinho de pelúcia pediria para comer?', 'Deixe o bichinho responder com uma voz engraçada.'),
('24-lev-pe', '2-4'::momentos.age_band, 'leve', 'Como o seu pé diria bom dia?', 'Mostre um cumprimento com o pé e convide a criança a inventar outro.'),
('24-lev-esconder', '2-4'::momentos.age_band, 'leve', 'Onde uma formiguinha brincaria de esconde-esconde aqui?', 'Aponte dois lugares pequenos para ajudar a escolher.'),
('24-med-de-novo', '2-4'::momentos.age_band, 'medio', 'O que você gostaria de fazer de novo comigo?', 'Lembre primeiro uma brincadeira curtinha que fizeram juntos.'),
('24-med-risada', '2-4'::momentos.age_band, 'medio', 'Quem fez você rir hoje?', 'Conte quem fez você rir e imite a risada.'),
('24-med-mostrar', '2-4'::momentos.age_band, 'medio', 'O que você quer me mostrar agora?', 'Pode ser um brinquedo, um desenho ou um movimento; acompanhe sem corrigir.'),
('24-med-descanso', '2-4'::momentos.age_band, 'medio', 'Onde você gosta de descansar?', 'Deixe a criança apontar; se quiser, sentem ali um instante.'),
('24-med-convite', '2-4'::momentos.age_band, 'medio', 'Como você me chama para brincar?', 'Mostre seu jeito de convidar e espere o jeito dela.'),
('24-med-ajudou', '2-4'::momentos.age_band, 'medio', 'O que alguém ajudou você a fazer hoje?', 'Se não lembrar, conte uma ajuda pequena que recebeu.'),
('56-lev-porta', '5-7'::momentos.age_band, 'leve', 'Se uma porta da casa levasse para um lugar impossível, onde daria?', 'Escolha uma porta de verdade e abra a aventura com uma frase.'),
('56-lev-chuva', '5-7'::momentos.age_band, 'leve', 'Se chovessem brinquedos por um minuto, o que cairia primeiro?', 'Conte sua escolha e invente o barulho da chuva.'),
('56-lev-bicho-novo', '5-7'::momentos.age_band, 'leve', 'Que nome teria um bicho metade gato, metade jacaré?', 'Desenhe no ar uma parte do bicho antes de ouvir o nome.'),
('56-lev-mensagem', '5-7'::momentos.age_band, 'leve', 'O que você diria para uma árvore que acabou de acordar?', 'Cumprimente a árvore primeiro com uma voz diferente.'),
('56-lev-objeto', '5-7'::momentos.age_band, 'leve', 'Qual objeto daqui daria um ótimo super-herói?', 'Escolha um objeto comum e invente um poder engraçado.'),
('56-lev-planeta', '5-7'::momentos.age_band, 'leve', 'Como seria um planeta onde todo mundo anda pulando?', 'Façam juntos um pulo pequeno para começar a imaginar.'),
('56-med-orgulho', '5-7'::momentos.age_band, 'medio', 'O que você fez recentemente e gostou de conseguir?', 'Conte uma coisa pequena que você aprendeu, sem comparar resultados.'),
('56-med-convite', '5-7'::momentos.age_band, 'medio', 'Como você gosta que eu convide você para brincar?', 'Ouça a preferência e combine de tentar desse jeito outro dia.'),
('56-med-surpresa', '5-7'::momentos.age_band, 'medio', 'O que surpreendeu você hoje?', 'Conte primeiro uma surpresa pequena do seu dia.'),
('56-med-juntos', '5-7'::momentos.age_band, 'medio', 'Qual cantinho daqui combina com uma brincadeira nossa?', 'Apontem o lugar; não precisa começar a brincar agora.'),
('56-med-ensinar', '5-7'::momentos.age_band, 'medio', 'Qual regra de uma brincadeira você mudaria?', 'Deixe a criança liderar, mesmo que a regra fique boba.'),
('56-med-cuidado', '5-7'::momentos.age_band, 'medio', 'O que deixa um dia difícil um pouco melhor?', 'Compartilhe uma ideia sua e aceite que a resposta dela seja diferente.'),
('56-fun-espaco', '5-7'::momentos.age_band, 'fundo', 'Quando você quer ficar perto e quando quer um tempo só seu?', 'Conte que as duas vontades são permitidas e escute sem insistir.'),
('56-fun-nao', '5-7'::momentos.age_band, 'fundo', 'Tem alguma brincadeira para a qual você queria poder dizer não?', 'Agradeça a sinceridade e respeite a escolha. Também vale passar a pergunta.'),
('56-fun-confianca', '5-7'::momentos.age_band, 'fundo', 'O que faz você se sentir seguro comigo?', 'Dê um exemplo concreto seu e escute sem pedir uma resposta bonita.'),
('56-fun-mudanca', '5-7'::momentos.age_band, 'fundo', 'Tem algo na nossa rotina que você gostaria de mudar?', 'Escolha uma mudança pequena que vocês possam experimentar.'),
('56-fun-escutar', '5-7'::momentos.age_band, 'fundo', 'Como eu posso perceber melhor quando você quer me contar uma coisa?', 'Não interrompa a resposta; combinem um sinal simples se isso ajudar.'),
('56-fun-orgulho', '5-7'::momentos.age_band, 'fundo', 'De que momento nosso você gosta de lembrar?', 'Conte uma lembrança sua e aceite qualquer lembrança que vier.')
on conflict (slug) do update set age_band = excluded.age_band, level = excluded.level, question = excluded.question, tip = excluded.tip;
